Start / Stop all
stake-house/wagyu pull request #51
Opened 2021-06-24 21:12 UTC by RomiRand

2021-06-25 14:25 UTC, colfax23 requested changes
Hey - thanks for submitting!  This will definitely be helpful.  Added some comments in case you have some time to revisit.  Let me know if you have any questions.

2021-06-25 14:25 UTC, colfax23 commented on src/react/commands/RocketPool.ts
> +const stopRocketPool = async() => {
Nice!  Reading this I was wondering why I hadn't already written these, and it looks like I did below (however I dont call them during the install).  If you have a chance you can use the below implementation of startNodes and stopNodes instead.

2021-06-25 14:25 UTC, colfax23 commented on src/react/commands/RocketPool.ts
> +  await stopRocketPool();
Per the above comment, lets call the below implementation here :)

2021-06-25 14:25 UTC, colfax23 commented on src/react/pages/Status.tsx
> +import { Link } from 'react-router-dom'
Mistaken import?

2021-06-25 14:25 UTC, colfax23 commented on src/react/pages/Status.tsx
> +            <th><StartButton onClick={startRocketPool}>Start All</StartButton></th>
Awesome - so excited to see this :)

2021-06-25 14:25 UTC, colfax23 commented on webpack.react.config.js
> +  devtool: 'source-map',
Do you know what this is for?

2021-07-08 11:23 UTC, RomiRand commented on src/react/commands/RocketPool.ts
> +const stopRocketPool = async() => {
Whoops, sure. Fixed.

2021-07-08 11:23 UTC, RomiRand commented on src/react/pages/Status.tsx
> +import { Link } from 'react-router-dom'
Probably

2021-07-08 11:24 UTC, RomiRand commented on webpack.react.config.js
> +  devtool: 'source-map',
I played around with debugging and this was needed for some reason. Shouldn't be in release code though

2021-07-08 13:38 UTC, colfax23 requested changes
Looks great!  So close, just a couple small things.

2021-07-08 13:38 UTC, colfax23 commented on src/react/commands/RocketPool.ts
> +const stopRocketPool = async() => {
Awesome!  Can you remove these duplicate implementations?

2021-07-08 13:38 UTC, colfax23 commented on src/react/pages/Status.tsx
> +const StartButton = styled.button`
Can we reuse the style of the LogsButton so they look similar?  Also, I noticed that when the text changes the button size changes, which alters the spacing of the whole table.  Can you make it fixed so it doesnt change size?

2021-07-08 13:38 UTC, colfax23 commented on src/react/pages/Status.tsx
> +    if (computeEth1Status() != 2 && eth2BeaconContainerStatus != 2 && eth2ValidatorContainerStatus != 2)
nit: { }

2021-07-08 13:38 UTC, colfax23 commented on src/react/pages/Status.tsx
> +            <th colSpan='3'/>
I ran into a build error here, I think it should be {3} instead of '3'.  Does this work for you?

2021-07-09 14:35 UTC, colfax23 approved these changes
Looks great - thanks!

2021-07-09 14:35 UTC, merged